name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/thai-learning-demo@v2
      - name: Install Flutter
        run: git clone  ~/flutter
      - name: Setup Flutter
        run: ~/flutter/bin/flutter pub get
      - name: Build iOS
        run: ~/flutter/bin/flutter build ios --release
